# Generated by Django 3.1.7 on 2021-04-02 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20210401_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='twitter_link',
            field=models.URLField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
